apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foodfinder-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: foodfinder  
    spec:     # pod spec                  
      containers: 
      - name: foodfinder
        image: gcr.io/phineasrt/hello-world-image:v1 # image we pushed
        ports:
        - containerPort: 3000