apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foodfinder-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: foodfinder  
    spec:     # pod spec                  
      containers: 
      - name: foodfinder
        image: jonahrosenblum/foodfinder
        ports:
        - containerPort: 7500