apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodfinder-deployment
spec:
  selector:
    matchLabels:
      app: foodfinder
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: foodfinder  
    spec:     # pod spec                  
      containers: 
      - name: foodfinder
        image: gcr.io/jonah-starter-project/foodfinder:v11
        ports:
        - containerPort: 7500
        env:
        - name: PORT
          value: "7500"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: foodfinder-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 7500
    protocol: TCP
  selector:
    app: foodfinder